# wget -O "./assets/notes/raw/B0.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.B0.aiff"
# wget -O "./assets/notes/raw/C1.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.C1.aiff"
# wget -O "./assets/notes/raw/Db1.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Db1.aiff"
# wget -O "./assets/notes/raw/D1.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.D1.aiff"
# wget -O "./assets/notes/raw/Eb1.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Eb1.aiff"
# wget -O "./assets/notes/raw/E1.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.E1.aiff"
# wget -O "./assets/notes/raw/F1.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.F1.aiff"
# wget -O "./assets/notes/raw/Gb1.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Gb1.aiff "
# wget -O "./assets/notes/raw/G1.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.G1.aiff"
# wget -O "./assets/notes/raw/Ab1.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Ab1.aiff"
# wget -O "./assets/notes/raw/A1.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.A1.aiff"
# wget -O "./assets/notes/raw/Bb1.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Bb1.aiff"
# wget -O "./assets/notes/raw/B1.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.B1.aiff"
# wget -O "./assets/notes/raw/C2.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.C2.aiff"
# wget -O "./assets/notes/raw/Db2.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Db2.aiff "
# wget -O "./assets/notes/raw/D2.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.D2.aiff"
# wget -O "./assets/notes/raw/Eb2.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Eb2.aiff"
# wget -O "./assets/notes/raw/E2.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.E2.aiff"
# wget -O "./assets/notes/raw/F2.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.F2.aiff"
# wget -O "./assets/notes/raw/Gb2.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Gb2.aiff"
# wget -O "./assets/notes/raw/G2.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.G2.aiff"
# wget -O "./assets/notes/raw/Ab2.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Ab2.aiff"
# wget -O "./assets/notes/raw/A2.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.A2.aiff"
# wget -O "./assets/notes/raw/Bb2.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Bb2.aiff"
# wget -O "./assets/notes/raw/B2.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.B2.aiff"
# wget -O "./assets/notes/raw/C3.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.C3.aiff"
# wget -O "./assets/notes/raw/Db3.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Db3.aiff"
# wget -O "./assets/notes/raw/D3.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.D3.aiff"
# wget -O "./assets/notes/raw/Eb3.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Eb3.aiff"
# wget -O "./assets/notes/raw/E3.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.E3.aiff"
# wget -O "./assets/notes/raw/F3.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.F3.aiff"
# wget -O "./assets/notes/raw/Gb3.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Gb3.aiff"
# wget -O "./assets/notes/raw/G3.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.G3.aiff"
# wget -O "./assets/notes/raw/Ab3.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Ab3.aiff"
# wget -O "./assets/notes/raw/A3.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.A3.aiff"
# wget -O "./assets/notes/raw/Bb3.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Bb3.aiff"
# wget -O "./assets/notes/raw/B3.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.B3.aiff"
# wget -O "./assets/notes/raw/C4.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.C4.aiff"
# wget -O "./assets/notes/raw/Db4.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Db4.aiff"
# wget -O "./assets/notes/raw/D4.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.D4.aiff"
# wget -O "./assets/notes/raw/Eb4.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Eb4.aiff"
# wget -O "./assets/notes/raw/E4.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.E4.aiff"
# wget -O "./assets/notes/raw/F4.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.F4.aiff"
# wget -O "./assets/notes/raw/Gb4.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Gb4.aiff"
# wget -O "./assets/notes/raw/G4.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.G4.aiff"
# wget -O "./assets/notes/raw/Ab4.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Ab4.aiff"
# wget -O "./assets/notes/raw/A4.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.A4.aiff"
# wget -O "./assets/notes/raw/Bb4.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Bb4.aiff"
# wget -O "./assets/notes/raw/B4.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.B4.aiff"
# wget -O "./assets/notes/raw/C5.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.C5.aiff"
# wget -O "./assets/notes/raw/Db5.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Db5.aiff"
# wget -O "./assets/notes/raw/D5.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.D5.aiff"
# wget -O "./assets/notes/raw/Eb5.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Eb5.aiff"
# wget -O "./assets/notes/raw/E5.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.E5.aiff"
# wget -O "./assets/notes/raw/F5.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.F5.aiff"
# wget -O "./assets/notes/raw/Gb5.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Gb5.aiff"
# wget -O "./assets/notes/raw/G5.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.G5.aiff"
# wget -O "./assets/notes/raw/Ab5.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Ab5.aiff"
# wget -O "./assets/notes/raw/A5.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.A5.aiff"
# wget -O "./assets/notes/raw/Bb5.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Bb5.aiff"
# wget -O "./assets/notes/raw/B5.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.B5.aiff"
# wget -O "./assets/notes/raw/C6.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.C6.aiff"
# wget -O "./assets/notes/raw/Db6.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Db6.aiff"
# wget -O "./assets/notes/raw/D6.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.D6.aiff"
# wget -O "./assets/notes/raw/Eb6.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Eb6.aiff"
# wget -O "./assets/notes/raw/E6.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.E6.aiff"
# wget -O "./assets/notes/raw/F6.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.F6.aiff"
# wget -O "./assets/notes/raw/Gb6.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Gb6.aiff"
# wget -O "./assets/notes/raw/G6.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.G6.aiff"
# wget -O "./assets/notes/raw/Ab6.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Ab6.aiff"
# wget -O "./assets/notes/raw/A6.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.A6.aiff"
# wget -O "./assets/notes/raw/Bb6.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Bb6.aiff"
# wget -O "./assets/notes/raw/B6.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.B6.aiff"
# wget -O "./assets/notes/raw/C7.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.C7.aiff"
# wget -O "./assets/notes/raw/Db7.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Db7.aiff"
# wget -O "./assets/notes/raw/D7.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.D7.aiff"
# wget -O "./assets/notes/raw/Eb7.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Eb7.aiff"
# wget -O "./assets/notes/raw/E7.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.E7.aiff"
# wget -O "./assets/notes/raw/F7.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.F7.aiff"
# wget -O "./assets/notes/raw/Gb7.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Gb7.aiff"
# wget -O "./assets/notes/sraw/G7.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.G7.aiff"
# wget -O "./assets/notes/raw/Ab7.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Ab7.aiff"
# wget -O "./assets/notes/raw/A7.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.A7.aiff"
# wget -O "./assets/notes/raw/Bb7.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.Bb7.aiff"
# wget -O "./assets/notes/raw/B7.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.B7.aiff"
# wget -O "./assets/notes/raw/C8.aiff" "https://theremin.music.uiowa.edu/sound%20files/MIS/Piano_Other/piano/Piano.mf.C8.aiff"

./ffmpeg.exe -i "./assets/notes/raw/B0.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/B0.wav"
./ffmpeg.exe -i "./assets/notes/raw/C1.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/C1.wav"
./ffmpeg.exe -i "./assets/notes/raw/Db1.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Db1.wav"
./ffmpeg.exe -i "./assets/notes/raw/D1.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/D1.wav"
./ffmpeg.exe -i "./assets/notes/raw/Eb1.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Eb1.wav"
./ffmpeg.exe -i "./assets/notes/raw/E1.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/E1.wav"
./ffmpeg.exe -i "./assets/notes/raw/F1.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/F1.wav"
./ffmpeg.exe -i "./assets/notes/raw/Gb1.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Gb1.wav"
./ffmpeg.exe -i "./assets/notes/raw/G1.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/G1.wav"
./ffmpeg.exe -i "./assets/notes/raw/Ab1.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Ab1.wav"
./ffmpeg.exe -i "./assets/notes/raw/A1.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/A1.wav"
./ffmpeg.exe -i "./assets/notes/raw/Bb1.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Bb1.wav"
./ffmpeg.exe -i "./assets/notes/raw/B1.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/B1.wav"
./ffmpeg.exe -i "./assets/notes/raw/C2.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/C2.wav"
./ffmpeg.exe -i "./assets/notes/raw/Db2.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Db2.wav"
./ffmpeg.exe -i "./assets/notes/raw/D2.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/D2.wav"
./ffmpeg.exe -i "./assets/notes/raw/Eb2.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Eb2.wav"
./ffmpeg.exe -i "./assets/notes/raw/E2.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/E2.wav"
./ffmpeg.exe -i "./assets/notes/raw/F2.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/F2.wav"
./ffmpeg.exe -i "./assets/notes/raw/Gb2.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Gb2.wav"
./ffmpeg.exe -i "./assets/notes/raw/G2.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/G2.wav"
./ffmpeg.exe -i "./assets/notes/raw/Ab2.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Ab2.wav"
./ffmpeg.exe -i "./assets/notes/raw/A2.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/A2.wav"
./ffmpeg.exe -i "./assets/notes/raw/Bb2.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Bb2.wav"
./ffmpeg.exe -i "./assets/notes/raw/B2.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/B2.wav"
./ffmpeg.exe -i "./assets/notes/raw/C3.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/C3.wav"
./ffmpeg.exe -i "./assets/notes/raw/Db3.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Db3.wav"
./ffmpeg.exe -i "./assets/notes/raw/D3.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/D3.wav"
./ffmpeg.exe -i "./assets/notes/raw/Eb3.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Eb3.wav"
./ffmpeg.exe -i "./assets/notes/raw/E3.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/E3.wav"
./ffmpeg.exe -i "./assets/notes/raw/F3.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/F3.wav"
./ffmpeg.exe -i "./assets/notes/raw/Gb3.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Gb3.wav"
./ffmpeg.exe -i "./assets/notes/raw/G3.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/G3.wav"
./ffmpeg.exe -i "./assets/notes/raw/Ab3.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Ab3.wav"
./ffmpeg.exe -i "./assets/notes/raw/A3.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/A3.wav"
./ffmpeg.exe -i "./assets/notes/raw/Bb3.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Bb3.wav"
./ffmpeg.exe -i "./assets/notes/raw/B3.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/B3.wav"
./ffmpeg.exe -i "./assets/notes/raw/C4.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/C4.wav"
./ffmpeg.exe -i "./assets/notes/raw/Db4.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Db4.wav"
./ffmpeg.exe -i "./assets/notes/raw/D4.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/D4.wav"
./ffmpeg.exe -i "./assets/notes/raw/Eb4.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Eb4.wav"
./ffmpeg.exe -i "./assets/notes/raw/E4.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/E4.wav"
./ffmpeg.exe -i "./assets/notes/raw/F4.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/F4.wav"
./ffmpeg.exe -i "./assets/notes/raw/Gb4.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Gb4.wav"
./ffmpeg.exe -i "./assets/notes/raw/G4.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/G4.wav"
./ffmpeg.exe -i "./assets/notes/raw/Ab4.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Ab4.wav"
./ffmpeg.exe -i "./assets/notes/raw/A4.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/A4.wav"
./ffmpeg.exe -i "./assets/notes/raw/Bb4.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Bb4.wav"
./ffmpeg.exe -i "./assets/notes/raw/B4.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/B4.wav"
./ffmpeg.exe -i "./assets/notes/raw/C5.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/C5.wav"
./ffmpeg.exe -i "./assets/notes/raw/Db5.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Db5.wav"
./ffmpeg.exe -i "./assets/notes/raw/D5.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/D5.wav"
./ffmpeg.exe -i "./assets/notes/raw/Eb5.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Eb5.wav"
./ffmpeg.exe -i "./assets/notes/raw/E5.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/E5.wav"
./ffmpeg.exe -i "./assets/notes/raw/F5.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/F5.wav"
./ffmpeg.exe -i "./assets/notes/raw/Gb5.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Gb5.wav"
./ffmpeg.exe -i "./assets/notes/raw/G5.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/G5.wav"
./ffmpeg.exe -i "./assets/notes/raw/Ab5.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Ab5.wav"
./ffmpeg.exe -i "./assets/notes/raw/A5.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/A5.wav"
./ffmpeg.exe -i "./assets/notes/raw/Bb5.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Bb5.wav"
./ffmpeg.exe -i "./assets/notes/raw/B5.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/B5.wav"
./ffmpeg.exe -i "./assets/notes/raw/C6.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/C6.wav"
./ffmpeg.exe -i "./assets/notes/raw/Db6.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Db6.wav"
./ffmpeg.exe -i "./assets/notes/raw/D6.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/D6.wav"
./ffmpeg.exe -i "./assets/notes/raw/Eb6.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Eb6.wav"
./ffmpeg.exe -i "./assets/notes/raw/E6.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/E6.wav"
./ffmpeg.exe -i "./assets/notes/raw/F6.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/F6.wav"
./ffmpeg.exe -i "./assets/notes/raw/Gb6.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Gb6.wav"
./ffmpeg.exe -i "./assets/notes/raw/G6.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/G6.wav"
./ffmpeg.exe -i "./assets/notes/raw/Ab6.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Ab6.wav"
./ffmpeg.exe -i "./assets/notes/raw/A6.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/A6.wav"
./ffmpeg.exe -i "./assets/notes/raw/Bb6.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Bb6.wav"
./ffmpeg.exe -i "./assets/notes/raw/B6.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/B6.wav"
./ffmpeg.exe -i "./assets/notes/raw/C7.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/C7.wav"
./ffmpeg.exe -i "./assets/notes/raw/Db7.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Db7.wav"
./ffmpeg.exe -i "./assets/notes/raw/D7.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/D7.wav"
./ffmpeg.exe -i "./assets/notes/raw/Eb7.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Eb7.wav"
./ffmpeg.exe -i "./assets/notes/raw/E7.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/E7.wav"
./ffmpeg.exe -i "./assets/notes/raw/F7.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/F7.wav"
./ffmpeg.exe -i "./assets/notes/raw/Gb7.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Gb7.wav"
./ffmpeg.exe -i "./assets/notes/raw/G7.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/G7.wav"
./ffmpeg.exe -i "./assets/notes/raw/Ab7.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Ab7.wav"
./ffmpeg.exe -i "./assets/notes/raw/A7.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/A7.wav"
./ffmpeg.exe -i "./assets/notes/raw/Bb7.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/Bb7.wav"
./ffmpeg.exe -i "./assets/notes/raw/B7.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/B7.wav"
./ffmpeg.exe -i "./assets/notes/raw/C8.aiff" -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp"  "./assets/notes/C8.wav"